### ISSUE TITLE
Telegram connection model

### ISSUE THREAD

**Issue by eutampieri** [eutampieri/cardgamesbot#6]
The aim of this issue is to find a performant way to connect to Telegram while not relying on incomplete and non updated libraries and using ureq, which provides a safe HTTP client with minimal dependencies. Below are depicted two hypothetical model, which can be enhanced and discussed.
![Immagine PNG](https://user-images.githubusercontent.com/10284268/81113350-5f5edf80-8f20-11ea-9e21-610167cf0af2.png)
In the image above the two proposed connection models are depicted. The first one has two threads that communicate through a queue, while the second one (proposed by @samueleceroni) consists of one thread for each match, plus one thread to handle updates from Telegram. Also, there are multiple queues, one for each match.
In my opinion the advantage of the second model over the first is that less data has to travel through threads, and panics are less dangerous.

**Comment by Manuele99** [comment]
I'd suggest to replace the polling method with a simple webhook to reduce the number of useless http requests. Also replacing the queued system with an async callback infrastructure can optimize the BE operations, and simplify the flow management.

**Comment by eutampieri** [comment]
Maybe [Rust Channels](http://static.rust-lang.org/doc/master/std/sync/mpsc/index.html) could be used instead of the queue
